---
ec2_count: 1
ec2_sg: WordPress Powered by AMIMOTO
ec2_sg_description: Default AMIMOTO Single AMI Security Group
ec2_subnet: subnet-1464a04d
ec2_vpc_id: vpc-ebc1468e
ec2_region: us-east-1
ec2_image: ami-c58c1dd3
ec2_keypair: digitalcube-dev
ec2_instance_type: t2.nano
ec2_tag_name: Ansible
ec2_volume_size: 8
ec2_volume_type: gp2
ec2_device_name: /dev/sdb
