---
- name: Provision
  hosts: tag_Name_Ansible
  gather_facts: True
  become: yes
  roles:
    - { role: common, tags: [common] }
    - { role: sshd, tags: [sshd] }
    - { role: nginx, tags: [nginx] }
    # - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    # - { role: users, tags: [users] }
    # - { role: hosted-sites, tags: [hosted-sites] }
