---
- name: Terminate instances
  vars:
    terminate: false
  when: terminate
  hosts: tag_Name_Ansible
  connection: local
  tasks:
  - name: Terminate instances that were previously launched
    ec2:
      state: stopped
