# ==============================================================================
# Global
# ==============================================================================

www_root: /srv/www
apt_cache_valid_time: 86400
