# ==============================================================================
# Hosted Sites
# ==============================================================================

hosted_sites:
  exit.j2made.com:
    site_hosts:
      - exit.j2made.com
    local_path: ~/dev/exit.j2made.com
    cache:
      enabled: false
      duration: 30s
