# ==============================================================================
# Users
# ==============================================================================

web_user: web
web_group: nginx

users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
