---
- name: Create security group
  ec2_group:
    name: "{{ ec2_security_group }}"
    description: Default Web Server
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- name: Launch the new EC2 Instance
  ec2:
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: yes
    group: "{{ ec2_security_group }}"
    count: "{{ ec2_count }}"
    vpc_subnet_id: "{{ ec2_subnet }}"
    assign_public_ip: yes
    region: "{{ ec2_region }}"
  register: ec2

- name: Add the newly created EC2 instance(s) to host group
  add_host:
    groupname: "{{ ec2_tag_name }}"
    hostname: "{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"

- name: Add tag to instances
  ec2_tag:
    resource: "{{ item.id }}"
    region: "{{ ec2_region }}"
    state: present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: "{{ ec2_tag_name }}"

- name: Add Key
  authorized_key:
    user: ec2-user
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
