---
- name: Validate Ansible version
  assert:
    that:
     - "{{ ansible_version is defined }}"
     - "{{ ansible_version.full | version_compare(minimum_ansible_version, '>=') }}"
    msg: "Your Ansible version is too old. Please update from {{ ansible_version.full | default('< 1.6') }} to {{ minimum_ansible_version }} or above."

- name: Installing Packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-setuptools
    - python-pycurl
    - "@Development tools"
    - curl
    - git-core

- name: Install pip Packages
  easy_install:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - awscli

- name: Upgrade Packages
  yum:
    name: '*'
    state: latest

- name: Check current timezone
  shell: awk -F\" '{ print $2}' /etc/sysconfig/clock
  register: current_zone
  changed_when: False

- name: Set UTC timezone
  file: src=/usr/share/zoneinfo/"{{ default_timezone }}"  dest=/etc/localtime state=link force=yes
  when: current_zone.stdout != "{{ default_timezone }}"
