---
- name: Ensure SSH server is installed
  yum:
    pkg: openssh-server
    state: latest
    update_cache: true
  notify:
    - restart ssh

- name: Ensure SSHD is configured
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
    - restart sshd
